"""fix type of staffId

Revision ID: 4605b8fa7da6
Revises: 2fea24b8bd13
Create Date: 2025-04-10 00:28:04.919189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4605b8fa7da6'
down_revision = '2fea24b8bd13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.alter_column('StaffId',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.alter_column('StaffId',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
